project:
  type: website

website:
  title: "Ewan Buckingham"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ewanbuckingham
      - icon: twitter
        href: https://twitter.com/ewanbuckingham
      - icon: linkedin
        href: https://twitter.com/ewanbuckingham
      - icon: email
        href: https://twitter.com/ewanbuckingham
      
        
format:
  html:
    theme: litera
    css: styles.css

editor: visual

